// DAFTAR SISWA MASTER (REVISI)
// Sumber: data siswa.xlsx (Sheet1)
// Total: 224 Data Siswa

const SISWA_BARU = [
    { nama: "Aditya Ramadhani", kelas: "KELAS 10-1" },
    { nama: "Aira Nafisatul Ainiyah", kelas: "KELAS 10-1" },
    { nama: "Ajja Albar Jauj Apriss", kelas: "KELAS 10-1" },
    { nama: "Alderio Ilham Qodzafi", kelas: "KELAS 10-1" },
    { nama: "Aldy Kurniawan Saputra", kelas: "KELAS 10-1" },
    { nama: "Amelia Ng Jiaxin", kelas: "KELAS 10-1" },
    { nama: "Antonio Junior Liwa Putra", kelas: "KELAS 10-1" },
    { nama: "Aryan Dwi Nurbekti", kelas: "KELAS 10-1" },
    { nama: "Dafa Parvaiz Zechariah Windriyono", kelas: "KELAS 10-1" },
    { nama: "Dimas Maulana", kelas: "KELAS 10-1" },
    { nama: "Diva Alicia Putri", kelas: "KELAS 10-1" },
    { nama: "Era Fatravia", kelas: "KELAS 10-1" },
    { nama: "Fahza Aliya Putri", kelas: "KELAS 10-1" },
    { nama: "Faza Askia Tamma Al Faruq", kelas: "KELAS 10-1" },
    { nama: "Febri Ardiansyah Putra", kelas: "KELAS 10-1" },
    { nama: "Felcia Agasi", kelas: "KELAS 10-1" },
    { nama: "Fiza Arif Uqianus Fan", kelas: "KELAS 10-1" },
    { nama: "Ghina Jifara Wangi", kelas: "KELAS 10-1" },
    { nama: "Jessi Tirta Dharma Ayu Puspayogi", kelas: "KELAS 10-1" },
    { nama: "Keysha Anindita Suri Pratama", kelas: "KELAS 10-1" },
    { nama: "Leavy Aqeyla Ayatul Husna", kelas: "KELAS 10-1" },
    { nama: "M Andy Begarrt Prassetyo", kelas: "KELAS 10-1" },
    { nama: "Marsya Dwi Saputri", kelas: "KELAS 10-1" },
    { nama: "Mutiara Safitri Mustofa", kelas: "KELAS 10-1" },
    { nama: "Nazlafatul Azizah", kelas: "KELAS 10-1" },
    { nama: "Putri Rizqi Ria Sugiyarto", kelas: "KELAS 10-1" },
    { nama: "Rera Mustika Resima", kelas: "KELAS 10-1" },
    { nama: "Riska Novita Putri", kelas: "KELAS 10-1" },
    { nama: "Safa Tiara Ramadani", kelas: "KELAS 10-1" },
    { nama: "Seyla Erfa Amanda Putri", kelas: "KELAS 10-1" },
    { nama: "Wifa Riski Ramadani", kelas: "KELAS 10-1" },
    { nama: "Akhmad Fauzi Fadilah", kelas: "KELAS 10-2" },
    { nama: "Alvino Ganesha Putra", kelas: "KELAS 10-2" },
    { nama: "Ammar Sahadat Dirgantara", kelas: "KELAS 10-2" },
    { nama: "Anggita Fitri Fauziah", kelas: "KELAS 10-2" },
    { nama: "Aziziah Jacinda Ruela Mahsa Rahmadi", kelas: "KELAS 10-2" },
    { nama: "Baim", kelas: "KELAS 10-2" },
    { nama: "Dhaniel Arifin", kelas: "KELAS 10-2" },
    { nama: "Dina Aprilia", kelas: "KELAS 10-2" },
    { nama: "Eka Reza Ramadhani", kelas: "KELAS 10-2" },
    { nama: "Fahrizal Bahtiar Hamzah", kelas: "KELAS 10-2" },
    { nama: "Feliza Artha Jasmine", kelas: "KELAS 10-2" },
    { nama: "Galuh Saputri", kelas: "KELAS 10-2" },
    { nama: "Gantari Zia Bhumyamca", kelas: "KELAS 10-2" },
    { nama: "Hana Fitria", kelas: "KELAS 10-2" },
    { nama: "Kevin Juliano Sandra Pratama", kelas: "KELAS 10-2" },
    { nama: "Marvin Nazalul Alfizar", kelas: "KELAS 10-2" },
    { nama: "Moh Ridho Dzikrullah", kelas: "KELAS 10-2" },
    { nama: "Mohammad Arya Raditya", kelas: "KELAS 10-2" },
    { nama: "Mohm Anas Maliki", kelas: "KELAS 10-2" },
    { nama: "Muhammad Ariansyah", kelas: "KELAS 10-2" },
    { nama: "Mutiara Dwi Apriliani", kelas: "KELAS 10-2" },
    { nama: "Myisha Amelia Jauhari", kelas: "KELAS 10-2" },
    { nama: "Nabila Gabrela Pradita", kelas: "KELAS 10-2" },
    { nama: "Naila Zulfi Az Zahra", kelas: "KELAS 10-2" },
    { nama: "Nayla Mufida", kelas: "KELAS 10-2" },
    { nama: "Nova Widiyanti", kelas: "KELAS 10-2" },
    { nama: "Revy Maulida Hasanah", kelas: "KELAS 10-2" },
    { nama: "Rista Ayu Putri", kelas: "KELAS 10-2" },
    { nama: "Sofiatul Azizah", kelas: "KELAS 10-2" },
    { nama: "Widya Julita Saputri", kelas: "KELAS 10-2" },
    { nama: "Zahra Thusita", kelas: "KELAS 10-2" },
    { nama: "Zelvia Ayu Verasari", kelas: "KELAS 10-2" },
    { nama: "Alysa Rani Zalianti", kelas: "KELAS 10-3" },
    { nama: "Asyafa Zahra Salsabilla", kelas: "KELAS 10-3" },
    { nama: "Aulia Zulfalita Pratama", kelas: "KELAS 10-3" },
    { nama: "Catur Ahmad Hasyim", kelas: "KELAS 10-3" },
    { nama: "Cheisya Anjela Putri", kelas: "KELAS 10-3" },
    { nama: "Devi Wulan Savira", kelas: "KELAS 10-3" },
    { nama: "Dhea Bunga Aprillia", kelas: "KELAS 10-3" },
    { nama: "Dinda Sekar Arumni", kelas: "KELAS 10-3" },
    { nama: "Dinda Septiana Dewi", kelas: "KELAS 10-3" },
    { nama: "Ega Fabian Yafa", kelas: "KELAS 10-3" },
    { nama: "Fahrina Bunga Aprillia", kelas: "KELAS 10-3" },
    { nama: "Firdaus Ibnu Hadi", kelas: "KELAS 10-3" },
    { nama: "Franda Aprilia Wuri Hartono", kelas: "KELAS 10-3" },
    { nama: "Geysa Hasta Saputra", kelas: "KELAS 10-3" },
    { nama: "Gilang Fitrah Darmawan", kelas: "KELAS 10-3" },
    { nama: "Icha Izzatul Jannah", kelas: "KELAS 10-3" },
    { nama: "Moh Azizul Hilmi", kelas: "KELAS 10-3" },
    { nama: "Mohammad Vale Septino Rossi", kelas: "KELAS 10-3" },
    { nama: "Muh. Irfan", kelas: "KELAS 10-3" },
    { nama: "Nabila Putri Awalia", kelas: "KELAS 10-3" },
    { nama: "Naysila Dwi Sasa Bila Putri Suryanto", kelas: "KELAS 10-3" },
    { nama: "Putri Aura Margareta", kelas: "KELAS 10-3" },
    { nama: "Rahel Niluh Agustina", kelas: "KELAS 10-3" },
    { nama: "Ramadhan Tegar Pamuji", kelas: "KELAS 10-3" },
    { nama: "Risma Ainun Nafiah", kelas: "KELAS 10-3" },
    { nama: "Robby Jati Murti", kelas: "KELAS 10-3" },
    { nama: "Suci Lintang Kinasih", kelas: "KELAS 10-3" },
    { nama: "Valecia Anggraeni Sasmita Putri", kelas: "KELAS 10-3" },
    { nama: "Wahyu Rizky Ramdhani", kelas: "KELAS 10-3" },
    { nama: "Wanda Putri Aprilia", kelas: "KELAS 10-3" },
    { nama: "Yoriza Danish Silvierra", kelas: "KELAS 10-3" },
    { nama: "Amelia Junita Cahyani", kelas: "KELAS 10-4" },
    { nama: "Andrianu Dwi Putra Kusuma", kelas: "KELAS 10-4" },
    { nama: "Bayu Putra Ramadhan", kelas: "KELAS 10-4" },
    { nama: "Cahyarani Faturohmah", kelas: "KELAS 10-4" },
    { nama: "Citra Ayu Vergita", kelas: "KELAS 10-4" },
    { nama: "Disty Eka Febiana", kelas: "KELAS 10-4" },
    { nama: "Diva Puspita Sari", kelas: "KELAS 10-4" },
    { nama: "Ferdy Id Andry Yanto", kelas: "KELAS 10-4" },
    { nama: "Fitri Nur Aini", kelas: "KELAS 10-4" },
    { nama: "Iga Mahareza", kelas: "KELAS 10-4" },
    { nama: "Ketut Sony Loke Budi Wiguna", kelas: "KELAS 10-4" },
    { nama: "Mayla Aura Andini", kelas: "KELAS 10-4" },
    { nama: "Meyka Nindi Agustin", kelas: "KELAS 10-4" },
    { nama: "Moh. Rafka Eka Mannansyah", kelas: "KELAS 10-4" },
    { nama: "Mohammad Ibra Ravito", kelas: "KELAS 10-4" },
    { nama: "Mohraffi Alfaridzi Ardiansyah", kelas: "KELAS 10-4" },
    { nama: "Muhamad Artha Mauridho", kelas: "KELAS 10-4" },
    { nama: "Muhammad Wahyu Puji Nugraha", kelas: "KELAS 10-4" },
    { nama: "Naura Gellicia Tiffany", kelas: "KELAS 10-4" },
    { nama: "Okta Dwi Nuraini", kelas: "KELAS 10-4" },
    { nama: "Rahma Taufik Ridani", kelas: "KELAS 10-4" },
    { nama: "Raka Putra Anggara", kelas: "KELAS 10-4" },
    { nama: "Sandy Virzatullah", kelas: "KELAS 10-4" },
    { nama: "Selvia Junita", kelas: "KELAS 10-4" },
    { nama: "Shinta Metta Lestari Ningsih", kelas: "KELAS 10-4" },
    { nama: "Stefa Rina Putri Anindita", kelas: "KELAS 10-4" },
    { nama: "Suluh Prabandaru", kelas: "KELAS 10-4" },
    { nama: "Vanesa Septiana Putri", kelas: "KELAS 10-4" },
    { nama: "Wawendra Wahyu Bimarta", kelas: "KELAS 10-4" },
    { nama: "Wulan Ceisha Ramadani", kelas: "KELAS 10-4" },
    { nama: "Yeni Dwi Prastyani", kelas: "KELAS 10-4" },
    { nama: "Yuyun Alfiana", kelas: "KELAS 10-4" },
    { nama: "Aisyah Okta Livina Laurenz", kelas: "KELAS 10-5" },
    { nama: "Alfida Hildana Aprilia", kelas: "KELAS 10-5" },
    { nama: "Amiral Jordan Arva", kelas: "KELAS 10-5" },
    { nama: "Anggun Virma Virnanda Devi", kelas: "KELAS 10-5" },
    { nama: "Aura Cintya Arbiela Putri", kelas: "KELAS 10-5" },
    { nama: "Aura Kirana Maulida", kelas: "KELAS 10-5" },
    { nama: "Cesya Mawra Pawlina Sari", kelas: "KELAS 10-5" },
    { nama: "Dea Nofa Leona Dewi", kelas: "KELAS 10-5" },
    { nama: "Eko Harianto", kelas: "KELAS 10-5" },
    { nama: "Farelio Brilyan Syah", kelas: "KELAS 10-5" },
    { nama: "Frisya Maulida Santika", kelas: "KELAS 10-5" },
    { nama: "Geisha Dwi Aprilia", kelas: "KELAS 10-5" },
    { nama: "Gytha Athiva Qanita Azaria", kelas: "KELAS 10-5" },
    { nama: "Lenny Zhifilia Nugrahani", kelas: "KELAS 10-5" },
    { nama: "Maulana Ishak", kelas: "KELAS 10-5" },
    { nama: "Moh Fakhri Lutfi", kelas: "KELAS 10-5" },
    { nama: "Mohammad Soeltan Sofyan Arridho", kelas: "KELAS 10-5" },
    { nama: "Muhamad Fahrezi", kelas: "KELAS 10-5" },
    { nama: "Muhamad Nata Maurino", kelas: "KELAS 10-5" },
    { nama: "Muhammad Khoiron Thoifur A.", kelas: "KELAS 10-5" },
    { nama: "Nadifah Farhanatul Mabruroh", kelas: "KELAS 10-5" },
    { nama: "Nadin Sya Prawesti", kelas: "KELAS 10-5" },
    { nama: "Neng Ayu Javanza Quine Yuandri", kelas: "KELAS 10-5" },
    { nama: "Nurul Izzati", kelas: "KELAS 10-5" },
    { nama: "Putri Bunga Cahyani", kelas: "KELAS 10-5" },
    { nama: "Rafansyah Wahyu Pratama", kelas: "KELAS 10-5" },
    { nama: "Rega Tegar Maulana Hakiki", kelas: "KELAS 10-5" },
    { nama: "Senja Dinanti", kelas: "KELAS 10-5" },
    { nama: "Syerila Silfi Maulida Syafii", kelas: "KELAS 10-5" },
    { nama: "Tiara Ayu Sabrina", kelas: "KELAS 10-5" },
    { nama: "Wulidatul Afifah", kelas: "KELAS 10-5" },
    { nama: "Ajeng Ulandari", kelas: "KELAS 10-6" },
    { nama: "Annisa Putri Zhaki", kelas: "KELAS 10-6" },
    { nama: "Aurel Jihan Panesa", kelas: "KELAS 10-6" },
    { nama: "Aviza Kirana Putri", kelas: "KELAS 10-6" },
    { nama: "Bunga Rachmatyas Mahani", kelas: "KELAS 10-6" },
    { nama: "Chen Lixin Nur Zaskia", kelas: "KELAS 10-6" },
    { nama: "Dela Cahya Maulita", kelas: "KELAS 10-6" },
    { nama: "Devi Mareta", kelas: "KELAS 10-6" },
    { nama: "Elina Amelia Margareta", kelas: "KELAS 10-6" },
    { nama: "Holidatul Fitri", kelas: "KELAS 10-6" },
    { nama: "I Gede Putra Yasa", kelas: "KELAS 10-6" },
    { nama: "Kiki Rosa Kamila", kelas: "KELAS 10-6" },
    { nama: "Linda Tri Yuliyani", kelas: "KELAS 10-6" },
    { nama: "Lutfi Aril Prayoga", kelas: "KELAS 10-6" },
    { nama: "Meylanie Anggi Zaziva", kelas: "KELAS 10-6" },
    { nama: "Moh Danial Herdyansah", kelas: "KELAS 10-6" },
    { nama: "Mohammad Toriq Hidayah", kelas: "KELAS 10-6" },
    { nama: "Muhafreza Saputra", kelas: "KELAS 10-6" },
    { nama: "Muhammad Ibrahimmovic", kelas: "KELAS 10-6" },
    { nama: "Nanda Sasmita", kelas: "KELAS 10-6" },
    { nama: "Poni Agriandari", kelas: "KELAS 10-6" },
    { nama: "Rahma Intan Permadhani", kelas: "KELAS 10-6" },
    { nama: "Refan Abi Firmansyah", kelas: "KELAS 10-6" },
    { nama: "Riska Maulidi Ulfa", kelas: "KELAS 10-6" },
    { nama: "Saskia Putri Cahyaningtyas", kelas: "KELAS 10-6" },
    { nama: "Septian Surya Rhomadhoni", kelas: "KELAS 10-6" },
    { nama: "Sofyan Zahuri Abdullah", kelas: "KELAS 10-6" },
    { nama: "Syava Dyani Putri", kelas: "KELAS 10-6" },
    { nama: "Vana Aghista Ramadhani", kelas: "KELAS 10-6" },
    { nama: "Zelih Aurela", kelas: "KELAS 10-6" },
    { nama: "Dita Kharisma Dwi", kelas: "KELAS 10-6" },
    { nama: "Achmad Fairus Raditya", kelas: "KELAS 10-7" },
    { nama: "Ah Farel Yanuar D.S.", kelas: "KELAS 10-7" },
    { nama: "Alvian Marifatul Abror", kelas: "KELAS 10-7" },
    { nama: "Andika Prasetya", kelas: "KELAS 10-7" },
    { nama: "Anggun Tri Mulyani", kelas: "KELAS 10-7" },
    { nama: "Caca Herliana Putri", kelas: "KELAS 10-7" },
    { nama: "Dila Agustiya Nengseh", kelas: "KELAS 10-7" },
    { nama: "Fathir Lanang Y.", kelas: "KELAS 10-7" },
    { nama: "Feby Putri Sugiansyah", kelas: "KELAS 10-7" },
    { nama: "Flora Ayu Valencya", kelas: "KELAS 10-7" },
    { nama: "Fredyco Raka", kelas: "KELAS 10-7" },
    { nama: "Jayanti Bunga Lestari", kelas: "KELAS 10-7" },
    { nama: "Kayla Maretha Putri Puspitarini", kelas: "KELAS 10-7" },
    { nama: "Lavenia Vega Putri Manik", kelas: "KELAS 10-7" },
    { nama: "Moh Arlyn Dwi Andika", kelas: "KELAS 10-7" },
    { nama: "Moh. Rifki Nurhidayat", kelas: "KELAS 10-7" },
    { nama: "Mohamad Alfian Maulana", kelas: "KELAS 10-7" },
    { nama: "Mohamad Andrian Maulana", kelas: "KELAS 10-7" },
    { nama: "Muhamad Azam Mubarok", kelas: "KELAS 10-7" },
    { nama: "Muhamad Danar Izha Rohil", kelas: "KELAS 10-7" },
    { nama: "Muhammad Priya Daniel W.", kelas: "KELAS 10-7" },
    { nama: "Muzdhalifa", kelas: "KELAS 10-7" },
    { nama: "Nagita Nur Oktaviani", kelas: "KELAS 10-7" },
    { nama: "Naila Izza Nurjanah", kelas: "KELAS 10-7" },
    { nama: "Nora Sahbania Fachrozie", kelas: "KELAS 10-7" },
    { nama: "Ramadhan", kelas: "KELAS 10-7" },
    { nama: "Reyno Arventa Hadin Pratama", kelas: "KELAS 10-7" },
    { nama: "Salma Rahadatul Aisy", kelas: "KELAS 10-7" },
    { nama: "Septina Auliya Ramadani", kelas: "KELAS 10-7" },
    { nama: "Stefani Angelina Darmanota", kelas: "KELAS 10-7" },
    { nama: "Vierra Dipuspa Deshinta Sugiono", kelas: "KELAS 10-7" },
    { nama: "Salma Rahadatul Aisy", kelas: "KELAS 10-7" },
    { nama: "Septina Auliya Ramadani", kelas: "KELAS 10-7" },
    { nama: "Siti Putri Nur Aiyizah", kelas: "KELAS 10-7" },
    { nama: "Stefani Angelina Darmanota", kelas: "KELAS 10-7" },
    { nama: "Vierra Dipuspa Deshinta Sugiono", kelas: "KELAS 10-7" }
];